version: '3'
services:
  app:
    command: npm start
    ports:
      - '8080:8080'
    environment:
      PUBLIC_PATH: http://localhost:8080
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/opt/node_app/app
      - /opt/node_app/app/node_modules
